# .air.toml
[build]
  cmd = "go build -o ./tmp/oasrouter ./cmd/oasrouter"
  bin = "tmp/oasrouter"
  include_ext = ["go", "tpl", "tmpl"]
  delay = 500
  stop_on_error = true

[watch]
  includes = ["."]
  excludes = ["tmp"]

[log]
  level = "debug"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
